from __future__ import annotations
from telegram import Update
from telegram.constants import ParseMode
from telegram.ext import ContextTypes

DETAILED_HELP = (
    "<b>Sei Agent Bot Commands</b>\n\n"
    "/start - Start the bot and see a welcome message.\n\n"
    "/help - Show this help message with details about all commands.\n\n"
    "/ping - Check if the bot is online and see the server's response time.\n\n"
    "/chain - Show Sei network status, RPC endpoint, and connection status.\n\n"
    "/balance &lt;address&gt; - Show the balance for a given address.\n"
    "• Supports EVM addresses (0x...) and SEI addresses (sei1...)\n"
    "• Shows both SEI and usei amounts for better readability\n"
    "• Example: /balance 0x1234567890abcdef1234567890abcdef12345678\n"
    "• Example: /balance sei1abcdefghijklmnopqrstuvwxyz1234567890\n\n"
    "/watch &lt;address&gt; - Start watching a Sei address for new transactions.\n"
    "• You will get notified when a new transaction is detected.\n"
    "• Supports both EVM and SEI address formats\n"
    "• Example: /watch 0x1234567890abcdef1234567890abcdef12345678\n\n"
    "/unwatch &lt;address&gt; - Stop watching a Sei address.\n"
    "• Example: /unwatch 0x1234567890abcdef1234567890abcdef12345678\n\n"
    "/watches - List all Sei addresses you are currently watching.\n\n"
    "<b>Portfolio Management:</b>\n"
    "/portfolio_add &lt;address&gt; [label] - Add address to your portfolio.\n"
    "• Supports EVM (0x...) and SEI (sei1...) addresses\n"
    "• Optional label for easy identification\n"
    "• Example: /portfolio_add 0xabc... \"trading\"\n"
    "• Example: /portfolio_add sei1abc... \"cold storage\"\n\n"
    "/portfolio_rm &lt;address&gt; - Remove address from your portfolio.\n"
    "• Example: /portfolio_rm 0xabc...\n\n"
    "/portfolio - Show portfolio summary with balances and USD values.\n"
    "• Aggregates all your portfolio addresses\n"
    "• Shows individual and total USD values\n"
    "• Uses real-time price data\n\n"
    "<b>Portfolio Insights:</b>\n"
    "/insights - Portfolio risk analysis and insights.\n"
"• Concentration analysis and diversification check\n"
"• Volatility signals and risk assessment\n"
"• AI-powered advisory powered by ElizaOS\n"
"• One-line risk callouts\n\n"
    "/targets &lt;stable_pct&gt; - Set target stablecoin allocation.\n"
    "• Percentage between 0-100\n"
    "• Example: /targets 40\n\n"
    "/rebal - Get rebalancing advice based on current target.\n"
    "• Uses your set target (default 40%)\n"
    "• Provides actionable rebalancing suggestions\n\n"
    "<b>Portfolio Alerts:</b>\n"
    "/alerts_on &lt;drop_pct&gt; - Enable portfolio drop alerts.\n"
    "• Monitors portfolio value every 30 seconds\n"
    "• Alerts if portfolio drops by specified percentage\n"
    "• Example: /alerts_on 5 (warns on 5% drop)\n"
    "• Example: /alerts_on 10 (warns on 10% drop)\n\n"
    "/alerts_off - Disable portfolio drop alerts.\n"
    "• Stops monitoring and removes alert settings\n\n"
    "<b>Network Information:</b>\n"
    "• Currently configured for Sei Testnet (Atlantic-2)\n"
    "• Chain ID: 13280x530\n"
    "• RPC: https://evm-rpc-testnet.sei-apis.com\n"
    "• Explorer: https://seitrace.com/?chain=atlantic-2\n\n"
    "<b>Features:</b>\n"
    "• ✅ Real-time balance checking\n"
    "• ✅ Address validation for both formats\n"
    "• ✅ Direct links to SeiTrace explorer\n"
    "• ✅ Connection status monitoring\n"
    "• ✅ Portfolio management and tracking\n"
    "• ✅ Risk analysis and insights\n"
"• ✅ Rebalancing advice\n"
"• ✅ Real-time portfolio alerts\n"
"• ✅ AI-powered advisory (ElizaOS)\n"
    "• ✅ Error handling and user feedback\n\n"
    "<b>Notes:</b>\n"
    "• EVM addresses are recommended for testnet testing\n"
    "• SEI native addresses are supported but may have limited functionality\n"
    "• The bot automatically validates address formats\n"
    "• Connection status is checked before balance queries"
)

async def help_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(DETAILED_HELP, parse_mode=ParseMode.HTML)
